# Praktikum IF3270 2023/2024

Tujuan praktikum IF3270 Pembelajaran Mesin:
1.   Peserta memahami rangkaian proses analitik data menggunakan pendekatan pembelajaran mesin. 
2.   Peserta memahami bahwa proses pengembangan model pembelajaran mesin juga ditentukan dari kualitas data, penanganan data, dan penentuan algoritma serta hyperparameter-nya; tidak cukup hanya dengan memastikan implementasi algoritma berjalan tanpa kesalahan.
3.   Peserta mampu menginterpretasikan hasil dari evaluasi model dalam proses analitik menggunakan pendekatan pembelajaran mesin.

Praktikum dilaksanakan secara berkelompok. Setiap kelompok terdiri atas 2 mahasiswa. Perhatikan bahwa terdapat berkas yang harus dikumpulkan saat keberjalanan praktikum untuk bagian A (25 April 2024, pukul 12.00 WIB) dan berkas yang dikumpulkan setelah waktu praktikum selesai untuk bagian B (25 April 2024, pukul 21.00 WIB).

Disediakan data yang sudah dibagi menjadi data latih (`df_train`), data validasi (`df_val`), dan data uji (`df_test`).

**Bagian 1**: (batas waktu: 25 April 2024, 12.00 WIB)

1. Buatlah _baseline_ dengan menggunakan model _logistic regression_.
2. Lakukan analisis data terkait hal berikut:
    - _duplicate value_,
    - _missing value_,
    - _outlier_,
    - _balance of data_.
3. Jelaskan rencana penanganan yang ada pada poin 2.
4. Jelaskan teknik _encoding_ yang digunakan terhadap data yang disediakan apabila dilakukan, disertai dengan alasan.
5. Buatlah desain eksperimen dengan menentukan hal berikut:
    - tujuan eksperimen,
    - variabel dependen dan independen,
    - strategi eksperimen,
    - skema validasi.
    
**Bagian 2**: (batas waktu: 25 April 2024, 21.00 WIB)

6. Implementasikan strategi eksperimen dan skema validasi yang telah ditentukan pada poin 5.
7. Berdasarkan hasil prediksi yang dihasilkan, buatlah kesimpulan analisis **hasil diabetes**.

---
Catatan:
- Jika terdapat perubahan jawaban pada poin 1—5 (contoh: perbedaan penanganan _outlier_), jelaskan pada laporan mengenai jawaban sebelum, jawaban sesudah, dan alasan pengubahan jawaban.
- Eksperimen dapat berupa penggantian model klasifikasi, pengaturan hyperparameter, model stacking, grid search, oversampling, undersampling, dan lain sebagainya. Semakin variatif eksperimen yang dilakukan, semakin baik.

## Dataset
`diabetes.csv` merupakan dataset yang telah dimodifikasi dari [Diabetes Health Indicators Dataset](https://www.kaggle.com/datasets/alexteboul/diabetes-health-indicators-dataset/) sebagai kumpulan indikator individu yang diperoleh dari survei untuk kasus diabetes. Dataset ini berguna untuk melakukan prediksi diabetes sehingga suatu individu dapat diketahui memiliki risiko tinggi diabetes atau tidak. Hal ini diperoleh dari fitur-fitur yang dapat dianalisis lebih lanjut sebelum mencapai kesimpulan.

Berikut adalah deskripsi singkat setiap kolom:

1. **HighBP**: Memiliki tekanan darah tinggi (BP: Blood Pressure) atau tidak
2. **HighChol**: Kolesterol tinggi atau tidak
3. **BMI**: Besaran Body Mass Index
4. **Smoker**: Perokok atau bukan perokok
5. **Stroke**: Pernah mengalami struk atau tidak
6. **HeartDiseaseorAttack**: Memiliki riwayat penyakit antara jantung koroner dan serangan jantung atau tidak sama sekali
7. **PhysActivity**: Aktif secara fisik dalam 30 hari terakhir atau tidak
8. **Fruits**: Mengonsumsi buah setiap hari atau tidak 
9. **Veggies**: Mengonsumsi sayur setiap hari atau tidak
10. **HvyAlcoholConsump**: Peminum berat alkohol atau bukan 
11. **AnyHealthcare**: Memiliki perlindungan kesehatan atau tidak, contohnya memiliki asuransi kesehatan
12. **GenHtlth**: Evaluasi mandiri terhadap kesehatan, skala 1-5 (1: Sangat baik, 2: Cukup Baik, 3: Baik, 4: Biasa saja, 5: Buruk)
13. **MentHlth**: Jumlah hari keadaan mental buruk dalam 30 hari terakhir (skala 0-30 hari)  
14. **PhysHlth**: Jumlah hari keadaan fisik buruk dalam 30 hari terakhir (skala 0-30 hari)
15. **DiffWalk**: Memiliki kesulitan berjalan atau menaiki tangga
16. **Sex**: (M) Male atau (F) Female
17. **Age**: 13 kategori umur (1: 18-24 tahun, 9: 60-64 tahun, 13: 80 tahun ke atas)
18. **Education**: Level edukasi skala 1-6 (1: Tidak pernah sekolah atau hanya TK, 2: SD, dst)
19. **Income**: Skala pendapatan 1-8
20. **Diabetes**: Apakah mengalami diabetes atau tidak (Kolom target)

_Deliverable_ yang akan dihasilkan adalah sebagai berikut:
1. berkas _notebook_ dengan format nama `PraktikumIF3270_M1_NIM1_NIM2.ipynb` untuk Bagian 1;
2. berkas _notebook_ dengan format nama `PraktikumIF3270_M2_NIM1_NIM2.ipynb` untuk Bagian 1 + Bagian 2; serta
3. berkas laporan dengan format nama `PraktikumIF3270_NIM1_NIM2.pdf` yang mencakup hal berikut:
    - hasil analisis data,
    - penanganan dari hasil analisis data,
    - justifikasi teknik-teknik yang dipilih,
    - perubahan yang dilakukan pada jawaban poin 1—5 jika ada,
    - desain eksperimen,
    - hasil eksperimen,
    - analisis dari hasil eksperimen,
    - kesimpulan,
    - pembagian tugas/kerja per anggota kelompok

Batas waktu pengumpulan:
- _Deliverable_ poin 1: Senin, 25 April 2023, pukul 12.00 WIB
- _Deliverable_ poin 2: Senin, 25 April 2023, pukul 21.00 WIB
- _Deliverable_ poin 3: Senin, 25 April 2023, pukul 21.00 WIB

# Praktikum IF3270 2023/2024

# BAGIAN 2

> Anggota Kelompok
Laila Bilbina Khoiru Nisa - 13521016
Raditya Naufal Abiyu - 13521022

## 5. Desain Eksperimen dalam Konteks Machine Learning:

### Tujuan Eksperimen
Tujuan dari eksperimen ini adalah untuk mengembangkan model machine learning yang dapat memprediksi risiko diabetes berdasarkan berbagai fitur kesehatan yang disediakan.

### Variabel Independen (Fitur)

- HighBP (Memiliki tekanan darah tinggi atau tidak)
- HighChol (Memiliki kolesterol tinggi atau tidak)
- BMI (Besaran Body Mass Index)
- Smoker (Perokok atau bukan perokok)
- HeartDiseaseorAttack (Memiliki riwayat penyakit antara jantung koroner dan serangan jantung atau tidak)
- PhysActivity (Aktif secara fisik dalam 30 hari terakhir atau tidak)
- Fruits (Mengonsumsi buah setiap hari atau tidak)
- Veggies (Mengonsumsi sayur setiap hari atau tidak)
- HvyAlcoholConsump (Peminum berat alkohol atau bukan)
- AnyHealthcare (Memiliki perlindungan kesehatan atau tidak)
- GenHtlth (Evaluasi mandiri terhadap kesehatan, skala 1-5)
- MentHlth (Jumlah hari keadaan mental buruk dalam 30 hari terakhir)
- PhysHlth (Jumlah hari keadaan fisik buruk dalam 30 hari terakhir)
- DiffWalk (Memiliki kesulitan berjalan atau menaiki tangga)
- Sex (Jenis kelamin: Male or Female)
- Age (Usia dalam 13 kategori umur)
- Education (Tingkat pendidikan, skala 1-6)
- Income (Skala pendapatan)

### Variabel Dependen
- Diabetes (Apakah mengalami diabetes atau tidak)

### Strategi Eksperimen

- Data akan dibagi menjadi set train dan set validation.
- Model machine learning, seperti logistic regression, decision tree, atau random forest, akan dilatih menggunakan set train.
- Kinerja model akan dievaluasi menggunakan set validation dengan metrik evaluasi seperti akurasi, presisi, recall, atau F1-score.
- Cross-validation mungkin digunakan untuk menghindari overfitting dan generalisir model.

### Skema Validasi

- Construction validity akan diperiksa dengan memastikan bahwa variabel independen yang dipilih mencerminkan faktor-faktor yang relevan untuk prediksi diabetes.
- Internal validity akan dijaga dengan memastikan bahwa model tidak mengalami overfitting terhadap data train.
- External validity akan diperiksa dengan memvalidasi kinerja model pada data validation yang tidak digunakan selama train.

## 6. Implementasikan strategi eksperimen dan skema validasi yang telah ditentukan pada poin 5.

In [1]:
! pip install imblearn
! pip install scikit-optimize 

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 258.0/258.0 kB 14.9 MB/s eta 0:00:00

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.7/107.7 kB 5.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 738.9/738.9 kB 39.8 MB/s eta 0:00:00

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip


In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import cross_val_score
import numpy as np
from scipy import stats

# Memuat dataset
df = pd.read_csv("diabetes.csv")

# encoding categorical menjadi numerical
df['Sex'] = df['Sex'].map({'F': 0.0, 'M': 1.0})
df['Diabetes'] = df['Diabetes'].astype(int)

# Membersihkan data
# Menghapus missing value
df.dropna(inplace=True)

# Menghapus duplicate rows
df.drop_duplicates(inplace=True)

# Menyeimbangkan data dengan oversampling SMOTE
X = df.drop(columns=['Diabetes'])
y = df['Diabetes']
smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X, y)

# Membagi data menjadi set train dan set validation
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [3]:
from sklearn.ensemble import RandomForestClassifier


modelF = RandomForestClassifier(bootstrap = True, criterion =  'gini', max_depth = 30, max_features = 'sqrt', min_samples_leaf= 4, min_samples_split= 2, n_estimators= 200)
modelF.fit(X_train, y_train)
y_pred = modelF.predict(X_val)
acc = accuracy_score(y_val, y_pred)
print(f"Accuracy: {acc}")
print(confusion_matrix(y_val, y_pred))
f1 = f1_score(y_val, y_pred)
print("F1 score: ", f1)
cv_score= cross_val_score(modelF, X_val, y_val, cv=5)
print("Mean CV score: ",cv_score.mean())

Accuracy: 0.9118577670634322
[[6318  284]
 [ 886 5786]]
F1 score:  0.9081776801130121
Mean CV score:  0.8912154769051298


In [5]:
y_pred = modelF.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc}")
print(confusion_matrix(y_test, y_pred))
f1 = f1_score(y_test, y_pred)
print("F1 score: ", f1)
cv_score= cross_val_score(modelF, X_test, y_test, cv=5)
print("Mean CV score: ",cv_score.mean())

Accuracy: 0.9138190803350811
[[7892  370]
 [1060 7271]]
F1 score:  0.9104683195592287
Mean CV score:  0.897908692731367


In [6]:
from sklearn.ensemble import GradientBoostingClassifier

modelG = GradientBoostingClassifier()

modelG.fit(X_train, y_train)
y_pred = modelG.predict(X_val)
acc = accuracy_score(y_val, y_pred)
print(f"Accuracy: {acc}")
print(confusion_matrix(y_val, y_pred))
f1 = f1_score(y_val, y_pred)
print("F1 score: ", f1)
cv_score= cross_val_score(modelG, X_val, y_val, cv=5)
print("Mean CV score: ",cv_score.mean())

Accuracy: 0.9019888503842097
[[6172  430]
 [ 871 5801]]
F1 score:  0.8991707354878711
Mean CV score:  0.901009455932629


In [8]:
y_pred = modelG.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc}")
print(confusion_matrix(y_test, y_pred))
f1 = f1_score(y_test, y_pred)
print("F1 score: ", f1)
cv_score= cross_val_score(modelG, X_test, y_test, cv=5)
print("Mean CV score: ",cv_score.mean())

Accuracy: 0.9055625866329174
[[7706  556]
 [1011 7320]]
F1 score:  0.9033133831060652
Mean CV score:  0.9035735398197783


In [9]:
from sklearn.ensemble import StackingClassifier

estimators = [
    ('rf', modelF),
    ('gbc', modelG)
]

modelS = StackingClassifier(estimators=estimators, final_estimator=RandomForestClassifier(bootstrap = True, criterion =  'gini', max_depth = 30, max_features = 'sqrt', min_samples_leaf= 4, min_samples_split= 2, n_estimators= 200))
modelS.fit(X_train, y_train)
y_pred = modelS.predict(X_val)
acc = accuracy_score(y_val, y_pred)
print(f"Accuracy: {acc}")
print(confusion_matrix(y_val, y_pred))
f1 = f1_score(y_val, y_pred)
print("F1 score: ", f1)
cv_score= cross_val_score(modelS, X_val, y_val, cv=5)
print("Mean CV score: ",cv_score.mean())

Accuracy: 0.9071869820702124
[[6274  328]
 [ 904 5768]]
F1 score:  0.9035087719298246
Mean CV score:  0.8974684553890867


In [10]:
y_pred = modelS.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc}")
print(confusion_matrix(y_test, y_pred))
f1 = f1_score(y_test, y_pred)
print("F1 score: ", f1)

Accuracy: 0.9103236304465738
[[7827  435]
 [1053 7278]]
F1 score:  0.9072550486163052


In [11]:
estimators = [
    ('rf', modelF),
    ('gbc', modelG)
]

modelSS = StackingClassifier(estimators=estimators, final_estimator=GradientBoostingClassifier())
modelSS.fit(X_train, y_train)
y_pred = modelSS.predict(X_val)
acc = accuracy_score(y_val, y_pred)
print(f"Accuracy: {acc}")
print(confusion_matrix(y_val, y_pred))
f1 = f1_score(y_val, y_pred)
print("F1 score: ", f1)
cv_score= cross_val_score(modelSS, X_val, y_val, cv=5)
print("Mean CV score: ",cv_score.mean())

Accuracy: 0.9136658128672593
[[6397  205]
 [ 941 5731]]
F1 score:  0.9091053299492386
Mean CV score:  0.901235104032289


In [12]:
y_pred = modelSS.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc}")
print(confusion_matrix(y_test, y_pred))
f1 = f1_score(y_test, y_pred)
print("F1 score: ", f1)

Accuracy: 0.9158078707888869
[[7970  292]
 [1105 7226]]
F1 score:  0.911855637579658


In [ ]:
# Hypertuning param untuk Random Forest Classifier
# from sklearn.model_selection import GridSearchCV

# param_grid = {
#     'n_estimators': [50, 100, 200],
#     'max_depth': [None, 10, 20, 30],
#     'min_samples_split': [2, 5, 10],
#     'min_samples_leaf': [1, 2, 4],
#     'max_features': ['sqrt', 'log2', None],
#     'bootstrap': [True, False],
#     'criterion': ['gini', 'entropy']
# }

# model = RandomForestClassifier()
# grid_search = GridSearchCV(model, param_grid, cv=5)
# grid_search.fit(X_train, y_train)
# print(f"Best parameter for random forest: {grid_search.best_params_}")

## 7. Berdasarkan hasil prediksi yang dihasilkan, buatlah kesimpulan analisis hasil diabetes.

Dari hasil prediksi yang diberikan oleh beberapa model ada 4 model yang memiliki performa terbaik yaitu Random Forest Classifier dengan parameter tuning, Gradient Boosting Classifier dan 2 model hasil stacking 2 model tersebut dengan final estimator yang berbeda. Dari hal tersebut dapat ditarik beberapa kesimpulan:

## Performa Model:
- Random Forest Classifier memiliki akurasi sebesar 91.26%. Ini menunjukkan bahwa model mampu dengan baik dalam mengklasifikasikan kedua kelas.
- Gradient Boosting Classifier memiliki akurasi sebesar 90.29%. Meskipun sedikit lebih rendah dari Random Forest, akurasi ini tetap menunjukkan kinerja yang baik dari model.
- Model gabungan Memiliki akurasi yang kurang lebih sama mendekati 91% dari kedua model dengan final estimator yang berbeda.
## Confusion Matrix:
- Random Forest Classifier memiliki +-300 prediksi salah untuk kelas negatif dan +-1000 prediksi salah untuk kelas positif.
- Gradient Boosting Classifier memiliki +-500 prediksi salah untuk kelas negatif dan +-1000 prediksi salah untuk kelas positif.
- Kedua model gabungan memiliki +-300 prediksi salah untuk kelas negatif dan +-1000 prediksi salah untuk kelas positif.
- Keempatnya menunjukkan kecenderungan untuk melakukan lebih baik dalam mengklasifikasikan kelas positif dibandingkan kelas negatif, tetapi perbedaannya tidak signifikan.
## Cross Validation Score:
Cross validation score mengukur seberapa baik model berkinerja pada data yang belum terlihat. Mean CV score dari semua model mendekati 90% atau bahkan melebihi 90% untuk beberapa model. Ini menunjukkan bahwa semua model memiliki kinerja yang stabil dan konsisten pada data yang tidak terlihat.
## F1 Score:
F1 score adalah metrik evaluasi yang mengukur kinerja model klasifikasi dengan memperhitungkan keseimbangan antara precision dan recall. Dalam kasus ini, semua model memiliki F1 score yang mendekati atau melebihi 90%, menunjukkan bahwa model-model tersebut memiliki kemampuan yang baik dalam mengklasifikasikan kedua kelas dengan baik.
## Perbandingan Model:
Meskipun Gradient Boosting Classifier memiliki akurasi yang sedikit lebih rendah daripada Random Forest Classifier, namun perbedaannya tidak signifikan. Secara umum, kedua model memiliki kinerja yang baik dalam mengklasifikasikan data diabetes. Secara teori hasil lebih baik bisa didapatkan apabila melakukan hyper parameter tuning untuk model Gradient Boosting Classifier. Parameter tuning untuk Gradient Boosting Classifier secara teori juga akan meningkatkan akurasi dan performa untuk kedua model gabungan

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=314804e3-a157-4407-beaa-fcd6e7c41784' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>